### ISSUE TITLE
API only works with CountryCode

### ISSUE THREAD

**Issue by haseeb-heaven** [Abdirahiim/covidtrackerapiwrapper#1]
API only works with country ISO 2-letter codes like IN for India etc.
Make it work for Country name aswell

**Comment by Abdirahiim** [comment]
I'm sorry but the libray can only fetch data  using the country code or ID because thats how the API it fetches the data from works

**Comment by Abdirahiim** [comment]
Sorry, I unintentionally approved the PR when I already committed new functions so the repo rejected it but I'll include you at the collaborators section, I'm sorry for the mishap

**Comment by haseeb-heaven** [comment]
okay no worries thanks for approving it .

**Comment by Abdirahiim** [comment]
@all-contributors please add @haseeb-heaven for code and examples.
