### ISSUE TITLE
What is Country ID

### ISSUE THREAD

**Issue by Raamyy** [Abdirahiim/covidtrackerapiwrapper#12]
> You can use the associated ID of a province or country to get the desired information

What are country IDs and what do they reference?

**Comment by Abdirahiim** [comment]
Sorry for not making it clear in the docs, by ID I mean the ID that the API labeled for each province and country, you can see which province or country has which ID on the API's url: http://coronavirus-tracker-api.herokuapp.com/v2/locations

**Comment by Raamyy** [comment]
I will add it.

**Comment by Abdirahiim** [comment]
Thanks, I appreciate it

**Comment by Abdirahiim** [comment]
@allcontributors please add @Raamyy for docs
