### ISSUE TITLE
Add A GitIgnore

### ISSUE THREAD

**Issue by khalidabuhakmeh** [Abdirahiim/covidtrackerapiwrapper#3]
Hey @Abdirahiim. This is a pretty cool project. I think you forgot to add a `.gitignore` file to your project and have committed most of the build artifacts to your repository.

Here is a great starter file. Just drop it at the root of your project and clean things up.

https://github.com/github/gitignore/blob/master/VisualStudio.gitignore

**Comment by Abdirahiim** [comment]
Thanks just added it
